# Generated by Django 5.2.8 on 2025-11-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='fans', to='teams.team', verbose_name='응원 팀'),
        ),
    ]
