# Generated by Django 5.2.8 on 2025-12-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('intent', models.CharField(choices=[('경기_일정', '경기 일정'), ('팀_정보', '팀 정보'), ('선수_정보', '선수 정보'), ('순위_정보', '순위 정보'), ('분석_요청', '분석 요청')], max_length=50, verbose_name='의도')),
                ('team_name', models.CharField(blank=True, default='', max_length=200, verbose_name='팀명')),
                ('player_name', models.CharField(blank=True, default='', max_length=200, verbose_name='선수명')),
                ('answer', models.TextField(verbose_name='답변')),
                ('search_results', models.JSONField(default=dict, verbose_name='검색 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 대화',
                'verbose_name_plural': 'AI 대화들',
                'ordering': ['-created_at'],
            },
        ),
    ]
