# Generated by Django 5.2.8 on 2025-11-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True, verbose_name='경기 ID')),
                ('competition', models.CharField(default='Premier League', max_length=200, verbose_name='대회명')),
                ('season', models.CharField(max_length=50, verbose_name='시즌')),
                ('matchday', models.IntegerField(blank=True, null=True, verbose_name='라운드')),
                ('match_date', models.DateTimeField(verbose_name='경기 날짜')),
                ('home_team_id', models.CharField(max_length=100, verbose_name='홈팀 ID')),
                ('home_team_name', models.CharField(max_length=200, verbose_name='홈팀명')),
                ('home_team_logo', models.URLField(blank=True, verbose_name='홈팀 로고')),
                ('away_team_id', models.CharField(max_length=100, verbose_name='원정팀 ID')),
                ('away_team_name', models.CharField(max_length=200, verbose_name='원정팀명')),
                ('away_team_logo', models.URLField(blank=True, verbose_name='원정팀 로고')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='홈팀 득점')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='원정팀 득점')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('live', '진행중'), ('finished', '종료'), ('postponed', '연기'), ('cancelled', '취소')], default='scheduled', max_length=20, verbose_name='경기 상태')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='경기장')),
                ('home_half_score', models.IntegerField(blank=True, null=True, verbose_name='홈팀 전반 득점')),
                ('away_half_score', models.IntegerField(blank=True, null=True, verbose_name='원정팀 전반 득점')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '경기',
                'verbose_name_plural': '경기들',
                'ordering': ['-match_date'],
                'indexes': [models.Index(fields=['match_date'], name='matches_mat_match_d_8426a6_idx'), models.Index(fields=['status'], name='matches_mat_status_a896a5_idx'), models.Index(fields=['home_team_id'], name='matches_mat_home_te_1944d1_idx'), models.Index(fields=['away_team_id'], name='matches_mat_away_te_4f491b_idx')],
            },
        ),
    ]
