# Generated by Django 5.2.8 on 2025-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('wiki_name', models.CharField(blank=True, max_length=200)),
                ('wiki_url', models.URLField(blank=True)),
                ('wiki_found', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=50)),
                ('position_abbr', models.CharField(max_length=10)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('team_id', models.CharField(blank=True, max_length=50)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('introduction', models.TextField(blank=True)),
                ('playing_style', models.TextField(blank=True)),
                ('career_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['name'],
            },
        ),
    ]
