# Generated by Django 5.2.8 on 2025-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('team_name', models.CharField(max_length=200)),
                ('league', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('team_name', models.CharField(max_length=100, verbose_name='팀명')),
                ('team_logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='팀 로고')),
                ('points', models.IntegerField(verbose_name='승점')),
                ('matches_played', models.IntegerField(verbose_name='경기수')),
                ('wins', models.IntegerField(verbose_name='승')),
                ('draws', models.IntegerField(verbose_name='무')),
                ('losses', models.IntegerField(verbose_name='패')),
                ('goals_for', models.IntegerField(verbose_name='득점')),
                ('goals_against', models.IntegerField(verbose_name='실점')),
                ('goal_difference', models.IntegerField(verbose_name='득실차')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '팀 순위',
                'verbose_name_plural': '팀 순위들',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['team_name', 'position', 'name'],
                'indexes': [models.Index(fields=['team_name'], name='teams_staff_team_na_33c1e9_idx'), models.Index(fields=['position'], name='teams_staff_positio_21b082_idx'), models.Index(fields=['name'], name='teams_staff_name_6bd6d9_idx')],
            },
        ),
    ]
