# Generated by Django 5.2.8 on 2025-11-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['team_name', 'position', 'name'],
                'indexes': [models.Index(fields=['team_name'], name='teams_staff_team_na_33c1e9_idx'), models.Index(fields=['position'], name='teams_staff_positio_21b082_idx'), models.Index(fields=['name'], name='teams_staff_name_6bd6d9_idx')],
            },
        ),
    ]
