# Generated by Django 5.2.8 on 2025-11-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('team_name', models.CharField(max_length=100, verbose_name='팀명')),
                ('team_logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='팀 로고')),
                ('points', models.IntegerField(verbose_name='승점')),
                ('matches_played', models.IntegerField(verbose_name='경기수')),
                ('wins', models.IntegerField(verbose_name='승')),
                ('draws', models.IntegerField(verbose_name='무')),
                ('losses', models.IntegerField(verbose_name='패')),
                ('goals_for', models.IntegerField(verbose_name='득점')),
                ('goals_against', models.IntegerField(verbose_name='실점')),
                ('goal_difference', models.IntegerField(verbose_name='득실차')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '팀 순위',
                'verbose_name_plural': '팀 순위들',
                'ordering': ['rank'],
            },
        ),
    ]
